schema_keyspace = """
CREATE KEYSPACE IF NOT EXISTS %s WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1}  AND durable_writes = true
"""

schema_table = """
CREATE TABLE IF NOT EXISTS %s.%s (
    id text,
    orgid int,
    partition int,
    name text,
    interval int,
    unit text,
    mtype text,
    tags set<text>,
    lastupdate int,
    PRIMARY KEY (partition, id)
) WITH compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
"""

schema_archive_table = """
CREATE TABLE IF NOT EXISTS %s.%s (
    id text,
    orgid int,
    partition int,
    name text,
    interval int,
    unit text,
    mtype text,
    tags set<text>,
    lastupdate int,
    archived_at int,
    PRIMARY KEY (partition, id)
) WITH compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
"""

schema_meta_record_table = """
CREATE TABLE IF NOT EXISTS %s.%s (
   batchid uuid,
   orgid int,
   expressions text,
   metatags text,
   PRIMARY KEY ((batchid, orgid), expressions)
)
"""

schema_meta_record_batch_table = """
CREATE TABLE IF NOT EXISTS %s.%s (
   orgid int,
   batchid uuid,
   createdat bigint,
   lastupdate bigint,
   PRIMARY KEY ((orgid), batchid)
)
"""