# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

[prune]
go-tests = true
non-go = true
unused-packages = true

[[constraint]]
  name = "github.com/Dieterbe/artisanalhistogram"
  branch = "master"

[[constraint]]
  name = "github.com/Dieterbe/profiletrigger"
  branch = "master"

[[constraint]]
  name = "github.com/Shopify/sarama"
  version = "1.10.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  # carbon-relay-ng needs this version. and tsdbgw includes both metrictank and carbon-relay-ng
  revision = "08e90462da344fbb3880e8e47a0ddacc37508579"

[[constraint]]
  name = "github.com/alyu/configparser"
  branch = "master"

[[constraint]]
  name = "github.com/bitly/go-hostpool"
  branch = "master"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.0"

[[constraint]]
  name = "github.com/dgryski/go-linlog"
  branch = "master"

[[constraint]]
  name = "github.com/dgryski/go-tsz"
  revision = "03b7d791f4fe79270d114e1ea6929332dbf028b7"

[[constraint]]
  name = "github.com/docker/docker"
  version = "v1.13.1"

[[constraint]]
  name = "github.com/go-macaron/binding"
  revision = "a453235199f8898e01647db8820f937a184fbd09"

[[constraint]]
  name = "github.com/gocql/gocql"
  revision = "d9815cdf0ff24e2efa9b8062f4f94a6dd347ae51"

[[constraint]]
  name = "github.com/golang/snappy"
  branch = "master"

[[constraint]]
  name = "github.com/hailocab/go-hostpool"
  branch = "master"

[[constraint]]
  name = "github.com/hashicorp/memberlist"
  branch = "master"

[[constraint]]
  name = "github.com/kisielk/og-rek"
  version = "v1.0.0"

[[constraint]]
  name = "github.com/kisielk/whisper-go"
  branch = "master"

[[constraint]]
  name = "github.com/metrics20/go-metrics20"
  branch = "master"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  branch = "master"

[[constraint]]
  name = "github.com/nsqio/go-nsq"
  revision = "642a3f9935f12cb3b747294318d730f56f4c34b4"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "^1"

[[constraint]]
  name = "github.com/raintank/dur"
  branch = "master"

[[constraint]]
  name = "github.com/raintank/gziper"
  branch = "master"

[[constraint]]
  name = "github.com/raintank/met"
  branch = "master"

[[constraint]]
  name = "github.com/raintank/misc"
  branch = "master"

[[constraint]]
  name = "github.com/raintank/schema"
  version = "^2"

[[constraint]]
  name = "github.com/rakyll/globalconf"
  branch = "master"

[[constraint]]
  name = "github.com/rs/cors"
  version = "1.0.0"

[[constraint]]
  name = "github.com/sergi/go-diff"
  version = "v1.0.0"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  branch = "master"

[[constraint]]
  name = "github.com/tinylib/msgp"
  version = "1.0.0-beta"

[[constraint]]
  name = "github.com/uber/jaeger-client-go"
  version = "2.15.0"
  source = "https://github.com/jaegertracing/jaeger-client-go.git"

[[override]]
  name = "github.com/uber/jaeger-lib"
  source = "https://github.com/jaegertracing/jaeger-lib.git"

[[constraint]]
  name = "gopkg.in/macaron.v1"
  version = "1.1.8"

[[constraint]]
  name = "github.com/prometheus/prometheus"
  source = "https://github.com/Dieterbe/prometheus.git"
  branch = "v2.1.0-tom-fix-testing-flags"

[[constraint]]
  name = "github.com/prometheus/procfs"
  revision = "75f2d6163c7a100bed6e971044ea3de30ee3a678"

[[override]]
  name = "golang.org/x/net"
  revision = "cbe0f9307d0156177f9dd5dc85da1a31abc5f2fb"
