version: '2'

services:
  metrictank:
    hostname: metrictank
    image: grafana/metrictank
    ports:
     - "6060:6060"
     - "2003:2003"
    volumes:
      - ../../build/metrictank:/usr/bin/metrictank
      - ../../scripts/config/metrictank-docker.ini:/etc/metrictank/metrictank.ini
      - ../../scripts/config/storage-schemas.conf:/etc/metrictank/storage-schemas.conf
      - ../../scripts/config/storage-aggregation.conf:/etc/metrictank/storage-aggregation.conf
      - ../../scripts/config/schema-store-cassandra.toml:/etc/metrictank/schema-store-cassandra.toml
      - ../../scripts/config/schema-idx-cassandra.toml:/etc/metrictank/schema-idx-cassandra.toml

    environment:
      WAIT_HOSTS: bigtable:8086
      WAIT_TIMEOUT: 60
      MT_HTTP_MULTI_TENANT: "false"
      MT_MEMORY_IDX_TAG_SUPPORT: "true"
      MT_CASSANDRA_ENABLED: "false"
      MT_CASSANDRA_IDX_ENABLED: "false"
      MT_BIGTABLE_STORE_ENABLED: "true"
      MT_BIGTABLE_IDX_ENABLED: "true"
      BIGTABLE_EMULATOR_HOST: bigtable:8086
    links:
     - bigtable

  bigtable:
    hostname: bigtable
    image: google/cloud-sdk
    command: gcloud beta emulators bigtable start --host-port=0.0.0.0:8086
    ports:
     - "8086:8086"

  graphite:
    hostname: graphite
    image: raintank/graphite-mt
    ports:
     - "8080:80"
    environment:
      GRAPHITE_CLUSTER_SERVERS: metrictank:6060
      GRAPHITE_STATSD_HOST: statsdaemon
      WSGI_PROCESSES: 4
      WSGI_THREADS: 25

  grafana:
    hostname: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-datasources:/etc/grafana/provisioning/datasources
      - ../cfg/grafana-dashboards-main-extra:/etc/grafana/provisioning/dashboards
      - ../../dashboards:/var/lib/grafana/dashboards

  statsdaemon:
    hostname: statsdaemon
    image: raintank/statsdaemon
    ports:
     - "8125:8125/udp"
    volumes:
     - "../cfg/statsdaemon.ini:/etc/statsdaemon.ini"
