version: '2'

services:
  metrictank0:
    hostname: metrictank0
    image: raintank/metrictank
    ports:
     - "6060:6060"
    volumes:
      - ../../build/metrictank:/usr/bin/metrictank
      - ./metrictank.ini:/etc/raintank/metrictank.ini
    environment:
      WAIT_HOSTS: kafka:9092,cassandra:9042
      WAIT_TIMEOUT: 30
      MT_KAFKA_MDM_IN_PARTITIONS: 0,1,2,3
      MT_KAFKA_CLUSTER_PARTITIONS: 0,1,2,3
      MT_INSTANCE: metrictank0
      MT_LOG_LEVEL: 2
      MT_CLUSTER_MODE: multi
      MT_CLUSTER_PRIMARY_NODE: "true"
      MT_CLUSTER_BIND_ADDR: "metrictank0:7946"
    links:
     - cassandra

  metrictank1:
    hostname: metrictank1
    image: raintank/metrictank
    ports:
      - "6061:6060"
    volumes:
      - ../../build/metrictank:/usr/bin/metrictank
      - ./metrictank.ini:/etc/raintank/metrictank.ini
    environment:
      WAIT_HOSTS: kafka:9092,cassandra:9042,metrictank0:6060
      WAIT_TIMEOUT: 30
      MT_KAFKA_MDM_IN_PARTITIONS: 0,1,2,3
      MT_KAFKA_CLUSTER_PARTITIONS: 0,1,2,3
      MT_INSTANCE: metrictank1
      MT_LOG_LEVEL: 2
      MT_CLUSTER_MODE: multi
      MT_CLUSTER_PEERS: metrictank0,metrictank2,metrictank3
      MT_CLUSTER_BIND_ADDR: "metrictank1:7946"
      MT_CLUSTER_PRIMARY_NODE: "false"
    links:
     - cassandra
     - metrictank0

  metrictank2:
    hostname: metrictank2
    image: raintank/metrictank
    ports:
      - "6062:6060"
    volumes:
      - ../../build/metrictank:/usr/bin/metrictank
      - ./metrictank.ini:/etc/raintank/metrictank.ini
    environment:
      WAIT_HOSTS: kafka:9092,cassandra:9042,metrictank0:6060
      WAIT_TIMEOUT: 30
      MT_KAFKA_MDM_IN_PARTITIONS: 4,5,6,7
      MT_KAFKA_CLUSTER_PARTITIONS: 4,5,6,7
      MT_INSTANCE: metrictank2
      MT_LOG_LEVEL: 2
      MT_CLUSTER_MODE: multi
      MT_CLUSTER_PEERS: metrictank0,metrictank1,metrictank3
      MT_CLUSTER_PRIMARY_NODE: "true"
      MT_CLUSTER_BIND_ADDR: "metrictank2:7946"
    links:
     - cassandra
     - metrictank0

  metrictank3:
    hostname: metrictank3
    image: raintank/metrictank
    ports:
      - "6063:6060"
    volumes:
      - ../../build/metrictank:/usr/bin/metrictank
      - ./metrictank.ini:/etc/raintank/metrictank.ini
    environment:
      WAIT_HOSTS: kafka:9092,cassandra:9042,metrictank0:6060
      WAIT_TIMEOUT: 30
      MT_KAFKA_MDM_IN_PARTITIONS: 4,5,6,7
      MT_KAFKA_CLUSTER_PARTITIONS: 4,5,6,7
      MT_INSTANCE: metrictank3
      MT_LOG_LEVEL: 2
      MT_CLUSTER_MODE: multi
      MT_CLUSTER_PEERS: metrictank0,metrictank1,metrictank2
      MT_CLUSTER_BIND_ADDR: "metrictank3:7946"
      MT_CLUSTER_PRIMARY_NODE: "false"
    links:
     - cassandra
     - metrictank0

  cassandra:
    hostname: cassandra
    image: cassandra:3.0.8
    environment:
      MAX_HEAP_SIZE: 1G
      HEAP_NEWSIZE: 256M
    ports:
     - "9042:9042"

  graphite-api:
    hostname: graphite-api
    image: raintank/graphite-metrictank
    ports:
     - "8080:8080"
    links:
     - metrictank0
     - statsdaemon
    volumes:
     - "./graphite-metrictank.yaml:/etc/graphite-metrictank/graphite-metrictank.yaml"

  grafana:
    hostname: grafana
    image: grafana/grafana:master
    ports:
      - "3000:3000"

  kafka:
    hostname: kafka
    image: raintank/kafka
    environment:
      ADVERTISED_HOST: kafka
      NUM_PARTITIONS: 8
    ports:
      - "2181:2181"
      - "9092:9092"
      - "9999:9999"
    volumes:
      - /tmp/kafka-logs

  statsdaemon:
    hostname: statsdaemon
    image: raintank/statsdaemon
    ports:
     - "8125:8125/udp"
    volumes:
     - "./statsdaemon.ini:/etc/statsdaemon.ini"

  # easiest to just use a separate graphite server for monitoring
  graphitemon:
    hostname: graphitemon
    image:  raintank/graphite-stack
    ports:
      - "2003:2003"
      - "443:443"
    volumes:
     - "./carbon.conf:/opt/graphite/conf/carbon.conf"
     - "./storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf"
