apiVersion: 1
datasources:
- name: metrictank
  type: graphite
  access: proxy
  orgId: 1
  url: http://metrictank0:6060
  isDefault: true
  jsonData:
     graphiteVersion: "1.1"
  version: 1
  editable: true
